
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    volumes:
      - ./src/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
#    depends_on:
#      - db
#    environment:
      # Django DB settings
#      POSTGRES_DB: mydb
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#      POSTGRES_HOST: db
#      POSTGRES_PORT: 5432

#  db:
#    image: postgres:15
#    container_name: django_db
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_DB: mydb
#      POSTGRES_USER: myuser
#      POSTGRES_PASSWORD: mypassword
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

#volumes:
#  postgres_data:
